check50:
  checks:
    # Horizontal win
    Horizontal win:
      - run: python3 connect4.py
        stdin: a\na\nb\nB\nc\nC\nD
        stdout: Congraduations player 1! You won!
        exit: 0
    # Horizontal win 2
    Horizontal win 2:
      - run: python3 connect4.py
        stdin: a\na\nb\nB\nc\nC\na\nd\na\nd
        stdout: Congraduations player 2! You won!
        exit: 0
    # Vertical win
    Vertical win:
      - run: python3 connect4.py
          stdin: a\ng\nf\ng\nd\ng\nd\ng
          stdout: Congraduations player 2! You won!
          exit: 0
    # Vertical win 2:
    Vertical win 2:
      - run: python3 connect4.py
          stdin: a\na\nb\na\nb\na\nb\na
          stdout: Congraduations player 2! You won!
          exit: 0
